### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by paulrzcz** [paulrzcz/HSvm#1]
1. Create README file.
2. Add description of libsvm.
3. Provide use cases for the library.
4. Make better function descriptions.

**Comment by unhammer** [comment]
how does it compare to https://github.com/aleator/Simple-SVM ?

**Comment by paulrzcz** [comment]
Honestly speaking, I don't know. I needed an SVM in my project, chose the library that existed on hackage, contacted the author, published his sources on github, upgraded to the latest version of libsvm and used in my project.

At first glance, it seems the only difference is that hsvm includes C source of libsvm and simple-svm relies on bindings-svm.

Though, as I said, I do not remember why I chose hsvm for my projects :)

**Comment by unhammer** [comment]
OK, also it seems svn-simple has a lot more dependencies, and is not in stackage. I just tried HSvm, and it seemed simple and easy to use :)
